Checkbox gives error when exercise data is set to null.
To investigate: 
- I've changed the Shortlisting page's initialisation. 
- shortlistingMethods has been set to null. 

Console Errors: 
 - Type Error / Vue Warn - Cannot read property 'indexOf' of null. 

Physical Errors: 
- Checking one box causes all boxes to be checked. 
- This causes more console errors such as: 
   - TypeError: this.$parent.inputValue.indexOf is not a function
   - [Vue warn]: Invalid prop: custom validator check failed for prop 
"value". 

The same issue does not happen when making a RadioGroup component 
initialize with a null value.